//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Abiturient
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заявление.
    /// </summary>
    // *** Start programmer edit section *** (Заявление CustomAttributes)

    // *** End programmer edit section *** (Заявление CustomAttributes)
    [BusinessServer("IIS.Abiturient.БизнесЛогика, Abiturient.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаявлениеE", new string[] {
            "ПорядковыйНомер as \'Порядковый номер\'",
            "ДатаПодачи as \'Дата подачи\'",
            "Абитуриент",
            "Абитуриент.Фамилия as \'Фамилия\'",
            "Абитуриент.Имя as \'Имя\'",
            "Абитуриент.Отчество as \'Отчество\'",
            "Абитуриент.Возраст as \'Возраст\'",
            "Абитуриент.Город as \'Город\'",
            "Абитуриент.Адрес as \'Адрес\'",
            "ПриемнаяКомиссия"}, Hidden=new string[] {
            "ПорядковыйНомер"})]
    [AssociatedDetailViewAttribute("ЗаявлениеE", "ЗаписьВЗаявлении", "ЗаписьВЗаявленииE", true, "", "", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаявлениеE", "Абитуриент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [MasterViewDefineAttribute("ЗаявлениеE", "ПриемнаяКомиссия", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Должность")]
    [View("ЗаявлениеL", new string[] {
            "ПорядковыйНомер as \'Порядковый номер\'",
            "ДатаПодачи as \'Дата подачи\'",
            "ПриемнаяКомиссия",
            "ПриемнаяКомиссия.Должность as \'Приемная комиссия\'",
            "Абитуриент",
            "Абитуриент.Фамилия as \'Фамилия\'",
            "Абитуриент.Имя as \'Имя\'",
            "Абитуриент.Отчество as \'Отчество\'",
            "Абитуриент.Возраст as \'Возраст\'",
            "Абитуриент.Город as \'Город\'",
            "Абитуриент.Адрес as \'Адрес\'"}, Hidden=new string[] {
            "ПорядковыйНомер",
            "ПриемнаяКомиссия",
            "Абитуриент"})]
    [AssociatedDetailViewAttribute("ЗаявлениеL", "ЗаписьВЗаявлении", "ЗаписьВЗаявленииE", true, "", "", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаявлениеL", "ПриемнаяКомиссия", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Должность")]
    [MasterViewDefineAttribute("ЗаявлениеL", "Абитуриент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    public class Заявление : ICSSoft.STORMNET.DataObject
    {
        
        private string fПорядковыйНомер;
        
        private System.DateTime fДатаПодачи;
        
        private IIS.Abiturient.ПриемнаяКомиссия fПриемнаяКомиссия;
        
        private IIS.Abiturient.Абитуриент fАбитуриент;
        
        private IIS.Abiturient.DetailArrayOfЗаписьВЗаявлении fЗаписьВЗаявлении;
        
        // *** Start programmer edit section *** (Заявление CustomMembers)

        // *** End programmer edit section *** (Заявление CustomMembers)

        
        /// <summary>
        /// ПорядковыйНомер.
        /// </summary>
        // *** Start programmer edit section *** (Заявление.ПорядковыйНомер CustomAttributes)

        // *** End programmer edit section *** (Заявление.ПорядковыйНомер CustomAttributes)
        [StrLen(255)]
        public virtual string ПорядковыйНомер
        {
            get
            {
                // *** Start programmer edit section *** (Заявление.ПорядковыйНомер Get start)
                
                // *** End programmer edit section *** (Заявление.ПорядковыйНомер Get start)
                string result = this.fПорядковыйНомер;
                // *** Start programmer edit section *** (Заявление.ПорядковыйНомер Get end)

                // *** End programmer edit section *** (Заявление.ПорядковыйНомер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявление.ПорядковыйНомер Set start)

                // *** End programmer edit section *** (Заявление.ПорядковыйНомер Set start)
                this.fПорядковыйНомер = value;
                // *** Start programmer edit section *** (Заявление.ПорядковыйНомер Set end)

                // *** End programmer edit section *** (Заявление.ПорядковыйНомер Set end)
            }
        }
        
        /// <summary>
        /// ДатаПодачи.
        /// </summary>
        // *** Start programmer edit section *** (Заявление.ДатаПодачи CustomAttributes)

        // *** End programmer edit section *** (Заявление.ДатаПодачи CustomAttributes)
        public virtual System.DateTime ДатаПодачи
        {
            get
            {
                // *** Start programmer edit section *** (Заявление.ДатаПодачи Get start)

                // *** End programmer edit section *** (Заявление.ДатаПодачи Get start)
                System.DateTime result = this.fДатаПодачи;
                // *** Start programmer edit section *** (Заявление.ДатаПодачи Get end)

                // *** End programmer edit section *** (Заявление.ДатаПодачи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявление.ДатаПодачи Set start)

                // *** End programmer edit section *** (Заявление.ДатаПодачи Set start)
                this.fДатаПодачи = value;
                // *** Start programmer edit section *** (Заявление.ДатаПодачи Set end)

                // *** End programmer edit section *** (Заявление.ДатаПодачи Set end)
            }
        }
        
        /// <summary>
        /// Заявление.
        /// </summary>
        // *** Start programmer edit section *** (Заявление.ПриемнаяКомиссия CustomAttributes)

        // *** End programmer edit section *** (Заявление.ПриемнаяКомиссия CustomAttributes)
        [PropertyStorage(new string[] {
                "ПриемнаяКомиссия"})]
        [NotNull()]
        public virtual IIS.Abiturient.ПриемнаяКомиссия ПриемнаяКомиссия
        {
            get
            {
                // *** Start programmer edit section *** (Заявление.ПриемнаяКомиссия Get start)

                // *** End programmer edit section *** (Заявление.ПриемнаяКомиссия Get start)
                IIS.Abiturient.ПриемнаяКомиссия result = this.fПриемнаяКомиссия;
                // *** Start programmer edit section *** (Заявление.ПриемнаяКомиссия Get end)

                // *** End programmer edit section *** (Заявление.ПриемнаяКомиссия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявление.ПриемнаяКомиссия Set start)

                // *** End programmer edit section *** (Заявление.ПриемнаяКомиссия Set start)
                this.fПриемнаяКомиссия = value;
                // *** Start programmer edit section *** (Заявление.ПриемнаяКомиссия Set end)

                // *** End programmer edit section *** (Заявление.ПриемнаяКомиссия Set end)
            }
        }
        
        /// <summary>
        /// Заявление.
        /// </summary>
        // *** Start programmer edit section *** (Заявление.Абитуриент CustomAttributes)

        // *** End programmer edit section *** (Заявление.Абитуриент CustomAttributes)
        [PropertyStorage(new string[] {
                "Абитуриент"})]
        [NotNull()]
        public virtual IIS.Abiturient.Абитуриент Абитуриент
        {
            get
            {
                // *** Start programmer edit section *** (Заявление.Абитуриент Get start)

                // *** End programmer edit section *** (Заявление.Абитуриент Get start)
                IIS.Abiturient.Абитуриент result = this.fАбитуриент;
                // *** Start programmer edit section *** (Заявление.Абитуриент Get end)

                // *** End programmer edit section *** (Заявление.Абитуриент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявление.Абитуриент Set start)

                // *** End programmer edit section *** (Заявление.Абитуриент Set start)
                this.fАбитуриент = value;
                // *** Start programmer edit section *** (Заявление.Абитуриент Set end)

                // *** End programmer edit section *** (Заявление.Абитуриент Set end)
            }
        }
        
        /// <summary>
        /// Заявление.
        /// </summary>
        // *** Start programmer edit section *** (Заявление.ЗаписьВЗаявлении CustomAttributes)

        // *** End programmer edit section *** (Заявление.ЗаписьВЗаявлении CustomAttributes)
        public virtual IIS.Abiturient.DetailArrayOfЗаписьВЗаявлении ЗаписьВЗаявлении
        {
            get
            {
                // *** Start programmer edit section *** (Заявление.ЗаписьВЗаявлении Get start)

                // *** End programmer edit section *** (Заявление.ЗаписьВЗаявлении Get start)
                if ((this.fЗаписьВЗаявлении == null))
                {
                    this.fЗаписьВЗаявлении = new IIS.Abiturient.DetailArrayOfЗаписьВЗаявлении(this);
                }
                IIS.Abiturient.DetailArrayOfЗаписьВЗаявлении result = this.fЗаписьВЗаявлении;
                // *** Start programmer edit section *** (Заявление.ЗаписьВЗаявлении Get end)

                // *** End programmer edit section *** (Заявление.ЗаписьВЗаявлении Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявление.ЗаписьВЗаявлении Set start)

                // *** End programmer edit section *** (Заявление.ЗаписьВЗаявлении Set start)
                this.fЗаписьВЗаявлении = value;
                // *** Start programmer edit section *** (Заявление.ЗаписьВЗаявлении Set end)

                // *** End programmer edit section *** (Заявление.ЗаписьВЗаявлении Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаявлениеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявлениеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявлениеE", typeof(IIS.Abiturient.Заявление));
                }
            }
            
            /// <summary>
            /// "ЗаявлениеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявлениеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявлениеL", typeof(IIS.Abiturient.Заявление));
                }
            }
        }
    }
}
