//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Abiturient
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Приемная комиссия.
    /// </summary>
    // *** Start programmer edit section *** (ПриемнаяКомиссия CustomAttributes)

    // *** End programmer edit section *** (ПриемнаяКомиссия CustomAttributes)
    [AutoAltered()]
    [Caption("Приемная комиссия")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПриемнаяКомиссияE", new string[] {
            "Должность as \'Должность\'"})]
    [View("ПриемнаяКомиссияL", new string[] {
            "Должность as \'Должность\'"})]
    public class ПриемнаяКомиссия : ICSSoft.STORMNET.DataObject
    {
        
        private string fДолжность;
        
        // *** Start programmer edit section *** (ПриемнаяКомиссия CustomMembers)

        // *** End programmer edit section *** (ПриемнаяКомиссия CustomMembers)

        
        /// <summary>
        /// Должность.
        /// </summary>
        // *** Start programmer edit section *** (ПриемнаяКомиссия.Должность CustomAttributes)

        // *** End programmer edit section *** (ПриемнаяКомиссия.Должность CustomAttributes)
        [StrLen(255)]
        public virtual string Должность
        {
            get
            {
                // *** Start programmer edit section *** (ПриемнаяКомиссия.Должность Get start)

                // *** End programmer edit section *** (ПриемнаяКомиссия.Должность Get start)
                string result = this.fДолжность;
                // *** Start programmer edit section *** (ПриемнаяКомиссия.Должность Get end)

                // *** End programmer edit section *** (ПриемнаяКомиссия.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриемнаяКомиссия.Должность Set start)

                // *** End programmer edit section *** (ПриемнаяКомиссия.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (ПриемнаяКомиссия.Должность Set end)

                // *** End programmer edit section *** (ПриемнаяКомиссия.Должность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПриемнаяКомиссияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриемнаяКомиссияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриемнаяКомиссияE", typeof(IIS.Abiturient.ПриемнаяКомиссия));
                }
            }
            
            /// <summary>
            /// "ПриемнаяКомиссияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриемнаяКомиссияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриемнаяКомиссияL", typeof(IIS.Abiturient.ПриемнаяКомиссия));
                }
            }
        }
    }
}
