//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Abiturient
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип заявления.
    /// </summary>
    // *** Start programmer edit section *** (ТипЗаявления CustomAttributes)

    // *** End programmer edit section *** (ТипЗаявления CustomAttributes)
    [AutoAltered()]
    [Caption("Тип заявления")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТипЗаявленияE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("ТипЗаявленияL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class ТипЗаявления : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (ТипЗаявления CustomMembers)

        // *** End programmer edit section *** (ТипЗаявления CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ТипЗаявления.Наименование CustomAttributes)

        // *** End programmer edit section *** (ТипЗаявления.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ТипЗаявления.Наименование Get start)

                // *** End programmer edit section *** (ТипЗаявления.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ТипЗаявления.Наименование Get end)

                // *** End programmer edit section *** (ТипЗаявления.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТипЗаявления.Наименование Set start)

                // *** End programmer edit section *** (ТипЗаявления.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ТипЗаявления.Наименование Set end)

                // *** End programmer edit section *** (ТипЗаявления.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТипЗаявленияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТипЗаявленияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТипЗаявленияE", typeof(IIS.Abiturient.ТипЗаявления));
                }
            }
            
            /// <summary>
            /// "ТипЗаявленияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТипЗаявленияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТипЗаявленияL", typeof(IIS.Abiturient.ТипЗаявления));
                }
            }
        }
    }
}
