//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Abiturient
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Факультет.
    /// </summary>
    // *** Start programmer edit section *** (Факультет CustomAttributes)

    // *** End programmer edit section *** (Факультет CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФакультетE", new string[] {
            "НазваниеФакультета as \'Название факультета\'",
            "НомерФакультета as \'Номер факультета\'",
            "Декан as \'Декан\'"}, Hidden=new string[] {
            "НомерФакультета"})]
    [View("ФакультетL", new string[] {
            "НазваниеФакультета as \'Название факультета\'",
            "НомерФакультета as \'Номер факультета\'",
            "Декан as \'Декан\'"}, Hidden=new string[] {
            "НомерФакультета"})]
    public class Факультет : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазваниеФакультета;
        
        private int fНомерФакультета;
        
        private string fДекан;
        
        // *** Start programmer edit section *** (Факультет CustomMembers)

        // *** End programmer edit section *** (Факультет CustomMembers)

        
        /// <summary>
        /// НазваниеФакультета.
        /// </summary>
        // *** Start programmer edit section *** (Факультет.НазваниеФакультета CustomAttributes)

        // *** End programmer edit section *** (Факультет.НазваниеФакультета CustomAttributes)
        [StrLen(255)]
        public virtual string НазваниеФакультета
        {
            get
            {
                // *** Start programmer edit section *** (Факультет.НазваниеФакультета Get start)

                // *** End programmer edit section *** (Факультет.НазваниеФакультета Get start)
                string result = this.fНазваниеФакультета;
                // *** Start programmer edit section *** (Факультет.НазваниеФакультета Get end)

                // *** End programmer edit section *** (Факультет.НазваниеФакультета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Факультет.НазваниеФакультета Set start)

                // *** End programmer edit section *** (Факультет.НазваниеФакультета Set start)
                this.fНазваниеФакультета = value;
                // *** Start programmer edit section *** (Факультет.НазваниеФакультета Set end)

                // *** End programmer edit section *** (Факультет.НазваниеФакультета Set end)
            }
        }
        
        /// <summary>
        /// НомерФакультета.
        /// </summary>
        // *** Start programmer edit section *** (Факультет.НомерФакультета CustomAttributes)

        // *** End programmer edit section *** (Факультет.НомерФакультета CustomAttributes)
        public virtual int НомерФакультета
        {
            get
            {
                // *** Start programmer edit section *** (Факультет.НомерФакультета Get start)

                // *** End programmer edit section *** (Факультет.НомерФакультета Get start)
                int result = this.fНомерФакультета;
                // *** Start programmer edit section *** (Факультет.НомерФакультета Get end)

                // *** End programmer edit section *** (Факультет.НомерФакультета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Факультет.НомерФакультета Set start)

                // *** End programmer edit section *** (Факультет.НомерФакультета Set start)
                this.fНомерФакультета = value;
                // *** Start programmer edit section *** (Факультет.НомерФакультета Set end)

                // *** End programmer edit section *** (Факультет.НомерФакультета Set end)
            }
        }
        
        /// <summary>
        /// Декан.
        /// </summary>
        // *** Start programmer edit section *** (Факультет.Декан CustomAttributes)

        // *** End programmer edit section *** (Факультет.Декан CustomAttributes)
        [StrLen(255)]
        public virtual string Декан
        {
            get
            {
                // *** Start programmer edit section *** (Факультет.Декан Get start)

                // *** End programmer edit section *** (Факультет.Декан Get start)
                string result = this.fДекан;
                // *** Start programmer edit section *** (Факультет.Декан Get end)

                // *** End programmer edit section *** (Факультет.Декан Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Факультет.Декан Set start)

                // *** End programmer edit section *** (Факультет.Декан Set start)
                this.fДекан = value;
                // *** Start programmer edit section *** (Факультет.Декан Set end)

                // *** End programmer edit section *** (Факультет.Декан Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФакультетE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФакультетE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФакультетE", typeof(IIS.Abiturient.Факультет));
                }
            }
            
            /// <summary>
            /// "ФакультетL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФакультетL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФакультетL", typeof(IIS.Abiturient.Факультет));
                }
            }
        }
    }
}
