/*flexberryautogenerated="true"*/
namespace IIS.Abiturient
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class СпециальностьL : BaseListForm<Специальность>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public СпециальностьL() : base(Специальность.Views.СпециальностьL)
        {
            EditPage = СпециальностьE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Specialnost/SpecialnostL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
