//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Abiturient
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Проверка даты подачи.
    /// </summary>
    // *** Start programmer edit section *** (ПроверкаДатыПодачи CustomAttributes)

    // *** End programmer edit section *** (ПроверкаДатыПодачи CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ПроверкаДатыПодачи : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (ПроверкаДатыПодачи CustomMembers)

        // *** End programmer edit section *** (ПроверкаДатыПодачи CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateЗаявление CustomAttributes)

        // *** End programmer edit section *** (OnUpdateЗаявление CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateЗаявление(IIS.Abiturient.Заявление UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateЗаявление)
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateЗаявление)
        }
    }
}
